### ISSUE TITLE
PodUnschedulable Cannot schedule pods: pod has unbound immediate PersistentVolumeClaims.

### ISSUE THREAD

**Issue by FasihZafar** [gesiscss/persistent_binderhub#28]
Hi all, I'm running into the following error while launching a repo. Any ideas on how to resolve this.  Thanks
Repo: https://github.com/binder-examples/r
My config.yaml:

```
binderhub:
  config:
    BinderHub:
      hub_url: http://<hubip>
      use_registry: true
      image_prefix: <dockerusername/binderhub->

  jupyterhub:
    hub:
      services:
        binder:
          # where binder runs
          url: "http://<binderip>"        
          apiToken: <token>
          oauth_redirect_uri: "http://<hubip>/services/binder/oauth_callback"
          oauth_client_id: "binder-oauth-client-test"

      config:
        JupyterHub:
          authenticator_class: dummy      

    proxy:
      secretToken: <token>

    singleuser:
      storage:
        dynamic:
          storageClass: <name for my storage class>

  registry:
    username: <dockerusername>
    password: <password>

```
